set(APE_SOURCE_DIR "${CMAKE_SOURCE_DIR}" CACHE PATH "Source root folder")
set(APE_OUTPUT_DIR_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/debug)
set(APE_OUTPUT_DIR_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/release)
set(APE_BIN_DIR "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}" CACHE PATH "Bin folder")

set(APE_THIRDPARTY_DIR "${APE_SOURCE_DIR}/thirdparty")
set(APE_CORE_DIR "${APE_SOURCE_DIR}/core" CACHE PATH "Core folder")
